### ISSUE TITLE
ios archive problem! (getting build but can't get archive!)

### ISSUE THREAD

**Issue by furkancelik** [tanersener/react-native-ffmpeg#66]
Hi bro, package successfully installed.
When I get the build, there is no error, but it gives an error when getting an archive..
step:
xCode>Product>Archive

**React Native Environment Info:**
```
  React Native Environment Info:
    System:
      OS: macOS 10.14.4
      CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
      Memory: 31.12 MB / 8.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 11.3.0 - /usr/local/bin/node
      Yarn: 1.12.3 - /usr/local/bin/yarn
      npm: 6.4.1 - /usr/local/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
      Android SDK:
        API Levels: 23, 25, 26, 27, 28
        Build Tools: 23.0.1, 25.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.3, 28.0.3
        System Images: android-27 | Intel x86 Atom_64, android-27 | Google APIs Intel x86 Atom, android-28 | Google APIs Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 10.2/10E125 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.8.3 => 16.8.3 
      react-native: 0.59.0 => 0.59.0 
    npmGlobalPackages:
      react-native-cli: 2.0.1
      react-native-create-library: 3.1.2
```

**my podfile**
```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'APPNAME' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for APPNAME
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'cxxreact',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
  ]

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'


  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'react-native-ffmpeg/full-gpl', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-video', path: '../node_modules/react-native-video'

  target 'APPNAMETests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'APPNAME-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for APPNAME-tvOS

  target 'APPNAME-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end


post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end

```

**package.json**
```
"react-native-ffmpeg": "^0.3.2",
```
Error message;
```
Undefined symbols for architecture armv7:
  "_OBJC_CLASS_$_MobileFFmpegConfig", referenced from:
      objc-class-ref in libreact-native-ffmpeg.a(RNFFmpegModule.o)
  "_OBJC_CLASS_$_MobileFFmpeg", referenced from:
      objc-class-ref in libreact-native-ffmpeg.a(RNFFmpegModule.o)
  "_OBJC_CLASS_$_ArchDetect", referenced from:
      objc-class-ref in libreact-native-ffmpeg.a(RNFFmpegModule.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
<img width="411" alt="Ekran Resmi 2019-05-17 08 11 13" src="https://user-images.githubusercontent.com/6446228/57904474-863d8500-787b-11e9-82f6-0ca337f97ae4.png">
<img width="581" alt="Ekran Resmi 2019-05-17 08 11 46" src="https://user-images.githubusercontent.com/6446228/57904476-86d61b80-787b-11e9-9bbe-cdc7da951e58.png">

**Comment by tanersener** [comment]
Hi Furkan, `Main Release` does not support 32 bit architectures. You need to install the `LTS` variant to support `armv7`. Can you update your dependencies using instructions in [2.4 LTS Release](https://github.com/tanersener/react-native-ffmpeg#24-lts-release) section?

**Comment by furkancelik** [comment]
@tanersener I rearranged the Podfile.
new podfile

```
# Uncomment the next line to define a global platform for your project
platform :ios, '9.3'

target 'APPNAME' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for APPNAME
  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'cxxreact',
    'CxxBridge', # Include this for RN >= 0.47
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket', # needed for debugging
  ]

  # To use CocoaPods with React Native, you need to add this specific Yoga spec as well
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  # Third party deps
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'


  pod 'react-native-camera', path: '../node_modules/react-native-camera'
  pod 'react-native-fast-image', :path => '../node_modules/react-native-fast-image'
  pod 'react-native-ffmpeg/full-gpl-lts', :podspec => '../node_modules/react-native-ffmpeg/ios/react-native-ffmpeg.podspec'
  pod 'RNFS', :path => '../node_modules/react-native-fs'
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'react-native-video', path: '../node_modules/react-native-video'

  target 'APPNAMETests' do
    inherit! :search_paths
    # Pods for testing
  end

end



post_install do |installer|
    installer.pods_project.targets.each do |target|
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
end

```

**then I ran the following commands respectively;**
```
cd ios/
rm -rf Pods Podfile.lock
cd ..
rm -rf node_modules

watchman watch-del-all && rm -rf $TMPDIR/haste-* &&  rm -rf $TMPDIR/metro-* && rm -rf $TMPDIR/react-*

yarn install
cd ios/
pod install


```

after xCode>Product>Clean Build Folder and archive but again error. 
New error message;
<img width="731" alt="Ekran Resmi 2019-05-17 09 50 47" src="https://user-images.githubusercontent.com/6446228/57908948-0ff44f00-788a-11e9-8a9f-285cd954fb00.png">
<img width="739" alt="Ekran Resmi 2019-05-17 09 51 01" src="https://user-images.githubusercontent.com/6446228/57908951-108ce580-788a-11e9-82e7-988c07886c6b.png">

**Comment by tanersener** [comment]
@furkancelik Can you please try again by deleting `ios/build` folder too?

**Comment by furkancelik** [comment]
@tanersener
already did "xCode > Product > Clean Build Folder"
No build file under ios directory.

**Comment by tanersener** [comment]
So what happens when you run `react-native run-ios` from the terminal?

**Comment by furkancelik** [comment]
The problem is now solved!
I think he couldn't create main.jsbundle because there wasn't enough disk space.
I have done it again 1-2 times to delete the ios directory and re-eject operations. After opening enough disk space, the archive could be retrieved.

Thank you for your quick messages.
react native ffmpeg nice work!
I congratulate you, bro..

**Comment by dkan10** [comment]
I've read the LTS issues, but still can't understand how to install LTS, please help me.

**Comment by tanersener** [comment]
Copied & pasted package documentation below. Which part is not clear?

------------

##### 2.3.2 iOS

- Edit `ios/Podfile` file and add package name as `subspec`. After that run `pod install` again.

    ```
    pod 'react-native-ffmpeg/<package name>', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'
    ```

#### 2.4 LTS Release

When a package name is not specified, `react-native-ffmpeg` is installed in the `Main Release` variant described in [LTS Releases](#5-lts-releases) section.

In order to install the `LTS` variant, install the `https-lts` package using instructions in `2.3` or append `-lts` to the package name you are using.

**Comment by dkan10** [comment]
This is the reason your tutorial is not clear. I'm usig React Native >= 0.60. I'm trying to build again. Thanks for quick reply and if you have time, please try to use my music app, and give me feedback if need :))

Link: https://apps.apple.com/us/app/youlisten-co/id1490895032?ls=1
##### 2.2.1 Basic

On React Native >= 0.60,
  
  - Add `use_native_modules!` to your `Podfile` and run `pod install`  

On React Native < 0.60,
  
  - Add `react-native-ffmpeg` pod to your `Podfile` and run `pod install`

    ```
    pod 'react-native-ffmpeg', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'
    ```
    
  - **DO NOT USE** `react-native link` **on iOS.** `react-native link` breaks Cocoapods dependencies.

**Comment by tanersener** [comment]
@dkan10 Copied & pasted package documentation below. As you can see yourself, none of these instructions is specific to react-native version? Moreover, the first two sentences of `2.3 Packages` section explains what should be expected from sections `2.1` and `2.2`. It's pretty clear that both of them installs the default package and you need to do something else to install a package. Good luck with your app.

------------

#### 2.3 Packages

Installation of `react-native-ffmpeg` using instructions in `2.1` and `2.2` enables the default package, which is based on `https` package. It is possible to enable other installed packages using the following steps.  

##### 2.3.2 iOS

- Edit `ios/Podfile` file and add package name as `subspec`. After that run `pod install` again.

    ```
    pod 'react-native-ffmpeg/<package name>', :podspec => '../node_modules/react-native-ffmpeg/react-native-ffmpeg.podspec'
    ```

#### 2.4 LTS Release

When a package name is not specified, `react-native-ffmpeg` is installed in the `Main Release` variant described in [LTS Releases](#5-lts-releases) section.

In order to install the `LTS` variant, install the `https-lts` package using instructions in `2.3` or append `-lts` to the package name you are using.

**Comment by Wqleonard** [comment]
Like https-lts-2.4?
